import { useState } from 'react';
import { Check, Globe, LoaderCircle, Send, ShieldCheck, Sparkles, Terminal } from 'lucide-react';
import { REQUIRED_CODEX_MODEL, runCodexAgent, type CodexEvent } from './lib/codex-agent';
import type { Progress } from './lib/storage';

type Message = { role: 'codex' | 'user'; text: string };
export function CodexView({ progress, setNotice }: { progress: Progress; setNotice: (notice: string) => void }) {
  const [messages, setMessages] = useState<Message[]>([{ role: 'codex', text: '我是项目内的 Codex 工作台。可以读取 867 Skill、本地笔记，并通过真实工具读取网页或创建待审批导入草稿。' }]);
  const [draft, setDraft] = useState(''); const [busy, setBusy] = useState(false); const [events, setEvents] = useState<CodexEvent[]>([]); const [pendingUrl, setPendingUrl] = useState('');
  const send = async (value = draft) => { const text = value.trim(); if (!text || busy) return; setDraft(''); setBusy(true); setMessages((current) => [...current, { role: 'user', text }]); setEvents([]); try { const reply = await runCodexAgent(progress.settings.baseUrl, progress.settings.apiKey, progress.settings.model, text, progress, (event) => setEvents((current) => [...current.filter((item) => item.name !== event.name), event])); setMessages((current) => [...current, { role: 'codex', text: reply }]); } catch (error) { setMessages((current) => [...current, { role: 'codex', text: `无法连接 API：${error instanceof Error ? error.message : String(error)}\n\n你仍可以通过 MCP 配置启动真实 Codex 工具。` }]); } finally { setBusy(false); } };
  const importPage = () => { const url = pendingUrl.trim(); if (!url) return; setPendingUrl(''); void send(`读取网页 ${url}，并准备一个网页导入草稿；不要直接写入正式知识库。`); };
  return <section className="content-stack"><div className="codex-layout"><section className="panel codex-chat"><div className="codex-banner"><Terminal size={18} /><div><strong>桌面安全桥接 · {REQUIRED_CODEX_MODEL}</strong><span>API Key 仅当前会话 · Base URL 已限制 · 工具受控</span></div></div><div className="coach-messages">{messages.map((message, index) => <div className={`chat-bubble ${message.role === 'codex' ? 'coach' : 'user'}`} key={`${message.role}-${index}`}><span>{message.role === 'codex' ? 'Codex' : '我'}</span>{message.text}</div>)}</div>{events.length > 0 && <div className="tool-events">{events.map((event) => <div key={event.name}><span>{event.status === 'running' ? <LoaderCircle size={14} className="spin" /> : <Check size={14} />}</span><strong>{event.name}</strong><small>{event.status === 'running' ? '执行中' : '已完成'}</small></div>)}</div>}<div className="coach-input"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void send()} placeholder="例如：搜索富营养化，并用采分点解释" /><button className="primary-button" disabled={busy || !draft.trim()} onClick={() => void send()}>{busy ? '执行中...' : '发送'} <Send size={15} /></button></div></section><aside className="panel codex-sidebar"><div className="section-heading"><div><span className="eyebrow">受控网页入口</span><h3>添加网页资料</h3></div><Globe size={20} /></div><p>仅读取公开网页并生成草稿；确认后才允许导入知识库。</p><div className="form-field"><label>公开网页 URL</label><input value={pendingUrl} onChange={(event) => setPendingUrl(event.target.value)} placeholder="https://example.com/article" /></div><button className="primary-button full-button" onClick={importPage} disabled={!pendingUrl.trim() || busy}>读取并准备草稿 <Globe size={15} /></button><div className="codex-capability"><ShieldCheck size={17} /><span>允许：本地 Skill、笔记、学习数据、网页草稿</span></div><div className="codex-capability"><Sparkles size={17} /><span>必须审批：正式入库、生成题目、构建任务</span></div><p className="codex-hint">API Key 不会写入 localStorage；桌面版通过 Tauri 安全桥接调用固定模型。</p></aside></div></section>;
}
