import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BarChart3, BookOpen, BrainCircuit, Check, ChevronLeft, ChevronRight, CircleHelp, FileText, Home, Menu, MessageCircle, PenLine, Search, Settings, ShieldCheck, Sparkles, Target, Terminal, X } from 'lucide-react';
import './styles.css';
import { cards, defaultQuestions, type Card } from './content';
import { bookChapters, bookPages, bookSource } from './book-index';
import { gradeAnswer, REQUIRED_MODEL } from './lib/ai';
import { dueMemory, loadProgress, saveProgress, scheduleMemory, type ChapterReview, type MemoryState, type Progress } from './lib/storage';
import { CoachView as RemoteCoachView } from './CoachView';
import { CodexView } from './CodexView';
import { MarkdownRenderer, ReaderFocusFrame, readerKeyAction } from './reader-renderer';

type View = 'home' | 'read' | 'cards' | 'review' | 'practice' | 'coach' | 'codex' | 'progress' | 'settings';
const titles: Record<View, string> = { home: '把知识变成得分点', read: '全文阅读与目录', cards: '主动回忆卡', review: '题库草稿审核', practice: '逐题练习', coach: '学习教练', codex: 'Codex 工作台', progress: '学习进度纵览', settings: '接口与数据设置' };
const feedback: Array<[MemoryState, string, string]> = [['again', '再来一次', '稍后再次出现'], ['hard', '困难', '留在当前轮，稍后再来'], ['good', '记住了', '移出当前轮并延长间隔'], ['easy', '很轻松', '移出当前轮并大幅延长']];

function App() {
  const [view, setView] = useState<View>('home');
  const [progress, setProgress] = useState<Progress>(() => loadProgress(defaultQuestions));
  const [query, setQuery] = useState('');
  const [mobileNav, setMobileNav] = useState(false);
  const [notice, setNotice] = useState('');
  const update = (next: Progress) => { setProgress(next); saveProgress(next); };
  const navigate = (next: View) => { setView(next); setMobileNav(false); setNotice(''); };
  const search = query.trim().toLowerCase();
  const due = dueMemory(progress.memory);
  const menu: Array<[View, string, typeof Home]> = [['home', '总览', Home], ['read', '全文阅读', BookOpen], ['cards', '主动回忆', BrainCircuit], ['review', '题库审核', FileText], ['practice', '开始练习', PenLine], ['coach', '学习教练', MessageCircle], ['codex', 'Codex 工作台', Terminal], ['progress', '学习进度', BarChart3], ['settings', '接口设置', Settings]];
  const saveReadingPosition = (pageNumber: number) => {
    const chapter = bookChapters.find((item) => pageNumber >= item.page && pageNumber <= item.endPage) ?? bookChapters.find((item) => item.title === progress.reading.chapterId) ?? bookChapters[0];
    const boundedPage = Math.min(bookPages[bookPages.length - 1]?.page ?? 1, Math.max(bookPages[0]?.page ?? 1, pageNumber));
    const percent = chapter ? Math.round((Math.min(chapter.endPage, Math.max(chapter.page, boundedPage)) - chapter.page + 1) / (chapter.endPage - chapter.page + 1) * 100) : 0;
    update({ ...progress, reading: { chapterId: chapter?.title ?? progress.reading.chapterId, pageNumber: boundedPage }, chapterProgress: chapter ? { ...progress.chapterProgress, [chapter.title]: { ...progress.chapterProgress[chapter.title], pageNumber: boundedPage, percent, lastReadAt: new Date().toISOString() } } : progress.chapterProgress });
  };
  const openChapter = (title: string) => {
    const chapter = bookChapters.find((item) => item.title === title);
    if (chapter) saveReadingPosition(progress.chapterProgress[chapter.title]?.pageNumber ?? chapter.page);
    navigate('read');
  };
  const currentPage = bookPages.find((page) => page.page === progress.reading.pageNumber) ?? bookPages[0];
  return <div className="app-shell"><aside className={mobileNav ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark">867</div><div><strong>环境学学习台</strong><span>本地优先 · 可解释复习</span></div></div><nav className="main-nav">{menu.map(([id, label, Icon]) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => navigate(id)}><Icon size={18} /><span>{label}</span>{id === 'cards' && due.length > 0 && <b className="badge">{due.length}</b>}</button>)}</nav><div className="side-tip"><Target size={17} /><div><strong>今日任务</strong><span>{due.length ? `有 ${due.length} 项到期，先做主动回忆。` : '阅读一章，再完成章节闯关。'}</span></div></div><div className="sidebar-footer"><span className="status-dot" />本地学习数据已保存</div></aside>{mobileNav && <button className="scrim" aria-label="关闭菜单" onClick={() => setMobileNav(false)} />}<main className="workspace"><header className="topbar"><button className="icon-button mobile-toggle" onClick={() => setMobileNav(true)} aria-label="打开菜单"><Menu size={20} /></button><div><span className="eyebrow">867 环境学 · 二期学习工作台</span><h1>{titles[view]}</h1></div><label className="search-box"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索全文、章节、卡片..." /></label></header>{notice && <div className="notice"><span>{notice}</span><button className="icon-button" onClick={() => setNotice('')}><X size={15} /></button></div>}{view === 'home' && <HomeView progress={progress} due={due.length} navigate={navigate} />}{view === 'read' && <ReadView progress={progress} update={update} page={currentPage} pageNumber={progress.reading.pageNumber} setPageNumber={saveReadingPosition} query={search} chapterId={progress.reading.chapterId} setNotice={setNotice} />}{view === 'cards' && <CardsView progress={progress} update={update} query={search} />}{view === 'review' && <ReviewView progress={progress} update={update} setNotice={setNotice} />}{view === 'practice' && <PracticeView progress={progress} update={update} setNotice={setNotice} />}{view === 'coach' && <RemoteCoachView progress={progress} setNotice={setNotice} />}{view === 'codex' && <CodexView progress={progress} setNotice={setNotice} />}{view === 'progress' && <ProgressPage progress={progress} onOpenChapter={openChapter} />}{view === 'settings' && <SettingsView progress={progress} update={update} setNotice={setNotice} />}</main></div>;
}

function HomeView({ progress, due, navigate }: { progress: Progress; due: number; navigate: (view: View) => void }) {
  const completedChapters = bookChapters.filter((chapter) => progress.read.includes(chapter.title)).length;
  const mastered = Object.values(progress.memory).filter((item) => item.repetitions >= 3).length;
  const activityDays = Object.keys(progress.activity).length;
  return <section className="content-stack"><div className="hero-card"><div className="hero-copy"><span className="eyebrow light">今日学习路线</span><h2>从“会看”到“会答”<br />每一步都留下证据。</h2><p>全文索引、主动回忆、章节闯关和进度趋势都在本地运行。</p><button className="primary-button" onClick={() => navigate(due ? 'cards' : 'read')}>{due ? '开始今日复习' : '打开全文阅读'} <ArrowRight size={17} /></button></div><div className="hero-graphic"><div className="hero-ring ring-one" /><div className="hero-ring ring-two" /><div className="hero-core">867</div></div></div><div className="stats-grid"><Stat label="索引页数" value={bookPages.length} suffix=" 页" hint="来源锚点可追溯" /><Stat label="完成章节" value={completedChapters} suffix=" / 12" hint="读完后进入闯关" /><Stat label="已掌握" value={mastered} suffix=" 项" hint="连续 3 次以上" /><Stat label="学习天数" value={activityDays} suffix=" 天" hint="本地活动记录" /></div><ProgressOverview progress={progress} /><div className="two-column"><section className="panel"><div className="section-heading"><div><span className="eyebrow">知识地图</span><h3>十二章治理闭环</h3></div><button className="text-button" onClick={() => navigate('read')}>查看全文 <ChevronRight size={15} /></button></div><div className="roadmap-list">{bookChapters.map((chapter, index) => <button className="roadmap-item" key={chapter.title} onClick={() => navigate('read')}><span className="step-number">{String(index + 1).padStart(2, '0')}</span><span><strong>{chapter.title}</strong><small>第 {chapter.page}–{chapter.endPage} 页 · {progress.read.includes(chapter.title) ? '已读完' : '待阅读'}</small></span><span className="roadmap-progress"><i style={{ width: `${progress.read.includes(chapter.title) ? 100 : 8}%` }} /></span><ChevronRight size={16} /></button>)}</div></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">答题链</span><h3>源 · 过程 · 后果 · 治理</h3></div><Sparkles size={19} className="gold-icon" /></div><div className="answer-chain">{[['源', '输入、排放与负荷'], ['过程', '迁移、转化与扩散'], ['后果', '质量、生态与暴露'], ['治理', '监测、控制与复盘']].map(([title, body], index) => <div className="chain-step" key={title}><span>0{index + 1}</span><strong>{title}</strong><p>{body}</p></div>)}</div></section></div></section>;
}

function ProgressOverview({ progress }: { progress: Progress }) {
  const days = useMemo(() => Array.from({ length: 30 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (29 - index)); const key = date.toISOString().slice(0, 10); return { key, count: progress.activity[key] ?? 0, label: `${date.getMonth() + 1}/${date.getDate()}` }; }), [progress.activity]);
  const recent7 = days.slice(-7).reduce((sum, day) => sum + day.count, 0);
  const recent30 = days.reduce((sum, day) => sum + day.count, 0);
  return <section className="panel progress-overview"><div className="section-heading"><div><span className="eyebrow">学习进度</span><h3>热力图与趋势</h3></div><span className="progress-count">近 7 天 {recent7} 次 · 近 30 天 {recent30} 次</span></div><div className="heatmap" aria-label="近三十天学习热力图">{days.map((day) => <span key={day.key} className={`heat-cell level-${Math.min(4, day.count)}`} title={`${day.label}：${day.count} 次`} />)}</div><div className="trend-chart" aria-label="近七天学习趋势">{days.slice(-7).map((day) => <div className="trend-column" key={day.key}><span style={{ height: `${Math.max(8, Math.min(100, day.count * 18))}%` }} /><small>{day.label.slice(2)}</small></div>)}</div></section>;
}

function ProgressPage({ progress, onOpenChapter }: { progress: Progress; onOpenChapter: (title: string) => void }) {
  const cardsByChapter = (title: string) => chapterCards(title);
  return <section className="content-stack"><div className="section-heading page-heading"><div><span className="eyebrow">本地学习数据</span><h2>学习进度纵览</h2><p>用章节热力、记忆卡掌握度和近期活动判断下一步，不用追逐排名。</p></div></div><ProgressOverview progress={progress} /><div className="progress-chapter-grid">{bookChapters.map((chapter, index) => { const chapterCardsList = cardsByChapter(chapter.title); const learned = chapterCardsList.filter((card) => progress.memory[card.id]?.repetitions); const mastered = chapterCardsList.filter((card) => (progress.memory[card.id]?.repetitions ?? 0) >= 3); const read = progress.read.includes(chapter.title); const readPercent = Math.max(progress.chapterProgress[chapter.title]?.percent ?? 0, read ? 100 : 0); const review = progress.chapterReview[chapter.title]; const status = review?.completed ? '已掌握' : review && !review.paused ? '闯关中' : read ? '待测试' : '未开始'; return <button className="progress-chapter-card" key={chapter.title} onClick={() => onOpenChapter(chapter.title)}><div className="chapter-card-top"><span className="step-number">{String(index + 1).padStart(2, '0')}</span><span className={`progress-status ${review?.completed ? 'done' : read ? 'active' : ''}`}>{status}</span></div><h3>{chapter.title}</h3><p>第 {chapter.page}–{chapter.endPage} 页 · {chapterCardsList.length} 张卡片</p><div className="chapter-metrics"><span>阅读 <b>{readPercent}%</b></span><span>记忆 <b>{chapterCardsList.length ? Math.round(learned.length / chapterCardsList.length * 100) : 0}%</b></span><span>掌握 <b>{chapterCardsList.length ? Math.round(mastered.length / chapterCardsList.length * 100) : 0}%</b></span></div><div className="progress-bar"><i style={{ width: `${chapterCardsList.length ? mastered.length / chapterCardsList.length * 100 : 0}%` }} /></div></button>; })}</div></section>;
}

function Stat({ label, value, suffix, hint }: { label: string; value: number; suffix: string; hint: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}<small>{suffix}</small></strong><em>{hint}</em></div>; }

function ReadView({ progress, update, page, pageNumber, setPageNumber, query, chapterId, setNotice }: { progress: Progress; update: (progress: Progress) => void; page: typeof bookPages[number]; pageNumber: number; setPageNumber: (number: number) => void; query: string; chapterId: string; setNotice: (notice: string) => void }) {
  const [focused, setFocused] = useState(false);
  const selectedChapter = bookChapters.find((chapter) => chapter.title === chapterId) ?? bookChapters[0];
  const matches = query ? bookPages.filter((item) => `${item.title} ${item.text}`.toLowerCase().includes(query)) : [];
  const jump = (number: number) => setPageNumber(Math.min(bookPages[bookPages.length - 1]?.page ?? 1, Math.max(bookPages[0]?.page ?? 1, number)));
  const selectChapter = (chapter: typeof bookChapters[number]) => {
    const saved = progress.chapterProgress[chapter.title];
    update({ ...progress, reading: { chapterId: chapter.title, pageNumber: saved?.pageNumber ?? chapter.page }, chapterProgress: { ...progress.chapterProgress, [chapter.title]: { ...saved, pageNumber: saved?.pageNumber ?? chapter.page, percent: saved?.percent ?? 0, lastReadAt: new Date().toISOString() } } });
  };
  const completeChapter = () => {
    if (!selectedChapter) return;
    const queue = chapterCards(selectedChapter.title).map((card) => card.id);
    const existing = progress.chapterReview[selectedChapter.title];
    const nextReview: ChapterReview = existing?.completed ? { queue, paused: false, completed: false } : existing ? { ...existing, paused: false } : { queue, paused: false, completed: queue.length === 0 };
    update({ ...progress, read: Array.from(new Set([...progress.read, selectedChapter.title])), chapterReview: { ...progress.chapterReview, [selectedChapter.title]: nextReview }, activity: touchActivity(progress.activity) });
    setNotice(queue.length ? `第 ${selectedChapter.title} 已读完，章节闯关已开始。` : '本章已读完，没有可用基线卡。');
  };
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const action = readerKeyAction(event.key, { isInput: event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement, isComposing: event.isComposing });
      if (action === 'previous-page') { event.preventDefault(); jump(pageNumber - 1); }
      if (action === 'next-page') { event.preventDefault(); jump(pageNumber + 1); }
      if (action === 'toggle-focus') { event.preventDefault(); setFocused((value) => !value); }
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [pageNumber]);
  return <section className="content-stack"><div className="section-heading page-heading"><div><span className="eyebrow">来源锚点 · {bookSource}</span><h2>全文阅读</h2><p>已从 `structured.md` 生成 {bookPages.length} 页内容；章节目录按原书 12 章定位，并保留原始页码。</p></div><div className="reader-controls"><button className="secondary-button" onClick={() => jump(pageNumber - 1)}><ChevronLeft size={16} />上一页</button><label>第 <input value={pageNumber} onChange={(event) => jump(Number(event.target.value) || 1)} /> / {bookPages.length} 页</label><button className="secondary-button" onClick={() => jump(pageNumber + 1)}>下一页<ChevronRight size={16} /></button><button className="secondary-button" onClick={() => setFocused((value) => !value)}>{focused ? '退出专注' : '专注阅读'}</button></div></div><div className="reader-layout"><aside className="panel toc"><h3>章节目录</h3>{bookChapters.map((chapter) => <button key={chapter.title} className={selectedChapter?.title === chapter.title ? 'toc-item active' : 'toc-item'} onClick={() => selectChapter(chapter)}><span>{chapter.page}</span><b>{chapter.title}</b><small>{progress.read.includes(chapter.title) ? '已读完' : `${chapter.endPage - chapter.page + 1} 页`}</small></button>)}{matches.length > 0 && <><hr /><h3>搜索结果</h3>{matches.slice(0, 24).map((item) => <button key={item.page} className="toc-item" onClick={() => jump(item.page)}><span>{item.page}</span>{item.title}</button>)}</>}</aside><ReaderFocusFrame focused={focused}><article className="reading-card source-reader"><div className="reading-meta"><span className="chapter-label">第 {page.page} 页</span><span>来源锚点：{page.sourceAnchor}</span></div><h3>{page.title}</h3><MarkdownRenderer markdown={page.text} query={query} />{selectedChapter && page.page >= selectedChapter.endPage && <div className="chapter-complete"><div><strong>读完本章了吗？</strong><p>确认后进入章节闯关；再次进入会恢复未完成的回炉队列。</p></div><button className="primary-button" onClick={completeChapter}>{progress.read.includes(selectedChapter.title) ? '重新进入章节闯关' : '完成阅读并开始闯关'} <ArrowRight size={16} /></button></div>}</article></ReaderFocusFrame></div>{selectedChapter && progress.read.includes(selectedChapter.title) && <ChapterChallenge progress={progress} update={update} chapter={selectedChapter} setNotice={setNotice} />}</section>;
}

function CardsView({ progress, update, query }: { progress: Progress; update: (progress: Progress) => void; query: string }) {
  const visible = cards.filter((card) => !query || `${card.title}${card.body}${card.tags.join('')}`.toLowerCase().includes(query));
  const [selectedId, setSelectedId] = useState(cards[0]?.id ?? '');
  const [revealed, setRevealed] = useState(false);
  const current = visible.find((card) => card.id === selectedId) ?? visible[0] ?? cards[0];
  if (!current) return <section className="content-stack"><EmptyState title="还没有记忆卡" body="请先运行 npm run content:index 生成本地基线卡。" /></section>;
  const review = (state: MemoryState) => { const memory = scheduleMemory(progress.memory[current.id], state, current.id, 'card', current.title); update({ ...progress, memory: { ...progress.memory, [current.id]: memory }, activity: touchActivity(progress.activity) }); setRevealed(false); };
  return <section className="content-stack"><div className="section-heading page-heading"><div><span className="eyebrow">主动回忆 · 间隔重复 + 遗忘曲线</span><h2>先回答，再看答案</h2><p>基线卡带有原书页码来源；good/easy 会移出当前章节轮次，again/hard 会回炉。</p></div></div><div className="card-training"><aside className="panel card-list">{visible.map((card) => <button key={card.id} className={card.id === current.id ? 'card-list-item active' : 'card-list-item'} onClick={() => { setSelectedId(card.id); setRevealed(false); }}><strong>{card.title}</strong><small>{progress.memory[card.id]?.repetitions ?? 0} 次 · {progress.memory[card.id] ? `下次 ${formatDate(progress.memory[card.id].dueAt)}` : '未学习'}</small></button>)}</aside><section className="panel recall-panel"><span className="pill">主动回忆卡</span><h2>{current.title}</h2><p className="recall-prompt">{current.prompt ?? '请用自己的话写出：这张卡如何迁移到一道题？'}</p>{revealed ? <div className="recall-answer"><strong>参考答案</strong><p>{current.answer ?? current.body}</p>{current.sourcePages && current.sourceAnchor && <small>来源：structured.md 第 {current.sourcePages[0]}–{current.sourcePages[1]} 页 · {current.sourceAnchor}</small>}{current.source && <small>来源：{current.source.file} 第 {current.source.startPage}–{current.source.endPage} 页 · {current.source.anchor}</small>}</div> : <button className="secondary-button reveal-button" onClick={() => setRevealed(true)}>显示参考答案</button>}<div className="memory-feedback"><span>复习反馈</span>{feedback.map(([state, label, hint]) => <button key={state} onClick={() => review(state)}><strong>{label}</strong><small>{hint}</small></button>)}</div>{progress.memory[current.id] && <MemorySummary item={progress.memory[current.id]} />}</section></div></section>;
}
function MemorySummary({ item }: { item: Progress['memory'][string] }) { return <div className="memory-summary"><span>掌握度：{Math.min(100, item.repetitions * 25 + Math.round((item.ease - 2) * 20))}%</span><span>间隔：{item.intervalDays.toFixed(1)} 天</span><span>下次：{formatDate(item.dueAt)}</span></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat('zh-CN', { month: 'numeric', day: 'numeric' }).format(new Date(value)); }

function ChapterChallenge({ progress, update, chapter, setNotice }: { progress: Progress; update: (progress: Progress) => void; chapter: typeof bookChapters[number]; setNotice: (notice: string) => void }) {
  const sourceCards = chapterCards(chapter.title);
  const state = progress.chapterReview[chapter.title] ?? { queue: sourceCards.map((card) => card.id), paused: false, completed: false };
  const queue = state.queue.filter((id) => sourceCards.some((card) => card.id === id));
  const [index, setIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const current = sourceCards.find((card) => card.id === queue[index]);
  const answer = progress.memory[current?.id ?? ''];
  if (state.completed || queue.length === 0) return <div className="challenge-card complete"><Check size={20} /><div><strong>{chapter.title} 闯关完成</strong><p>本轮卡片已移出队列；下次到期时会回到主动回忆。</p></div></div>;
  if (state.paused) return <div className="challenge-card"><div className="challenge-header"><div><span className="eyebrow">章节闯关已暂停</span><strong>{chapter.title}</strong></div><button className="primary-button" onClick={() => update({ ...progress, chapterReview: { ...progress.chapterReview, [chapter.title]: { ...state, paused: false } } })}>恢复本轮</button></div><p>队列已保留 {queue.length} 张卡片；恢复后从当前轮继续。</p></div>;
  const respond = (feedbackState: MemoryState) => {
    if (!current) return;
    const memory = scheduleMemory(progress.memory[current.id], feedbackState, current.id, 'card', current.title);
    const nextQueue = queue.filter((id) => id !== current.id);
    if (feedbackState === 'again') nextQueue.unshift(current.id);
    if (feedbackState === 'hard') nextQueue.push(current.id);
    const nextState = { ...state, queue: nextQueue, paused: false, completed: nextQueue.length === 0, completedAt: nextQueue.length === 0 ? new Date().toISOString() : state.completedAt };
    update({ ...progress, memory: { ...progress.memory, [current.id]: memory }, chapterReview: { ...progress.chapterReview, [chapter.title]: nextState }, activity: touchActivity(progress.activity) });
    const nextIndex = !nextQueue.length ? 0 : feedbackState === 'again' ? Math.min(index + 1, nextQueue.length - 1) : Math.min(index, nextQueue.length - 1);
    setIndex(nextIndex);
    setRevealed(false);
    if (!nextQueue.length) setNotice(`${chapter.title} 闯关完成！`);
  };
  const pause = () => { update({ ...progress, chapterReview: { ...progress.chapterReview, [chapter.title]: { ...state, queue, paused: true } } }); setNotice('章节闯关已暂停，下次进入会恢复当前轮。'); };
  return <div className="challenge-card"><div className="challenge-header"><div><span className="eyebrow">章节闯关 · {chapter.page}–{chapter.endPage} 页</span><strong>{chapter.title}</strong></div><button className="ghost-button" onClick={pause}>暂停</button></div><p>先独立回忆，再揭示答案；again/hard 回炉，good/easy 移出当前轮。</p>{current && <div className="challenge-prompt"><span className="pill">{index + 1} / {queue.length}</span><h3>{current.title}</h3><p>{current.prompt ?? '先口头或书面复述，再选择你对这张卡的掌握程度。'}</p><button className="secondary-button" onClick={() => setRevealed((value) => !value)}>{revealed ? '隐藏答案' : '揭示答案'}</button>{revealed && <div className="grade-result"><strong>参考答案</strong><p>{current.answer ?? current.body}</p></div>}{answer && <small>上次：{answer.lastFeedback ?? '未记录'} · 间隔 {answer.intervalDays.toFixed(1)} 天</small>}<div className="challenge-actions">{feedback.map(([stateKey, label]) => <button key={stateKey} className="secondary-button" disabled={!revealed} onClick={() => respond(stateKey)}>{label}</button>)}</div></div>}</div>;
}

function ReviewView({ progress, update, setNotice }: { progress: Progress; update: (progress: Progress) => void; setNotice: (notice: string) => void }) { const drafts = progress.questions.filter((question) => question.status === 'draft'); if (!drafts.length) return <section className="content-stack"><EmptyState title="没有待审核草稿" body="当前题库草稿已经全部处理。" /></section>; return <section className="content-stack"><div className="panel review-list">{drafts.map((question) => <div className="review-item" key={question.id}><div><span className="pill">{question.type}</span><h3>{question.title}</h3><p>{question.answer}</p></div><button className="primary-button" onClick={() => { update({ ...progress, questions: progress.questions.map((item) => item.id === question.id ? { ...item, status: 'approved' } : item) }); setNotice('题目已通过审核'); }}>通过并加入练习</button></div>)}</div></section>; }

function PracticeView({ progress, update, setNotice }: { progress: Progress; update: (progress: Progress) => void; setNotice: (notice: string) => void }) { const questions = progress.questions.filter((question) => question.status === 'approved'); const [index, setIndex] = useState(0); const [busy, setBusy] = useState(false); if (!questions.length) return <section className="content-stack"><EmptyState title="还没有正式题目" body="请先在题库数据中加入 approved 题目。" /></section>; const question = questions[index] ?? questions[0]; const answer = progress.answers[question.id] ?? ''; const submit = async () => { setBusy(true); try { const result = await gradeAnswer(progress.settings.baseUrl, progress.settings.apiKey, progress.settings.model, question.title, answer, question.answer, question.points); update({ ...progress, grades: { ...progress.grades, [question.id]: result }, memory: { ...progress.memory, [question.id]: scheduleMemory(progress.memory[question.id], 'good', question.id, 'question', question.title) }, activity: touchActivity(progress.activity) }); setNotice('批改完成，已安排下一次复习'); } catch (error) { setNotice(error instanceof Error ? error.message : '批改失败'); } finally { setBusy(false); } }; return <section className="content-stack"><div className="practice-layout"><aside className="panel question-rail"><span className="eyebrow">题目列表</span>{questions.map((item, itemIndex) => <button key={item.id} className={item.id === question.id ? 'question-nav active' : 'question-nav'} onClick={() => setIndex(itemIndex)}>{String(itemIndex + 1).padStart(2, '0')} · {item.title}</button>)}</aside><div className="answer-panel"><div className="question-meta"><span className="pill">{question.type}</span><span>{question.difficulty}</span></div><h2>{question.title}</h2><div className="points-box"><strong>采分点</strong><div className="tag-row">{question.points.map((point) => <span key={point}>{point}</span>)}</div></div><textarea value={answer} onChange={(event) => update({ ...progress, answers: { ...progress.answers, [question.id]: event.target.value } })} placeholder="先写出你的判断链条..." /><div className="answer-footer"><span>{answer.length} 字 · 本地保存</span><button className="primary-button" disabled={busy || !answer.trim()} onClick={submit}>{busy ? '批改中...' : '提交批改'} <Sparkles size={16} /></button></div>{progress.grades[question.id] && <div className="grade-result"><strong>最近反馈</strong><p>{progress.grades[question.id]}</p></div>}</div></div></section>; }

  function SettingsView({ progress, update, setNotice }: { progress: Progress; update: (progress: Progress) => void; setNotice: (notice: string) => void }) { const [draft, setDraft] = useState(progress.settings); const save = () => { update({ ...progress, settings: { ...draft, model: REQUIRED_MODEL } }); setNotice(`设置已保存；模型已锁定为 ${REQUIRED_MODEL}，API Key 仅保留在当前会话。`); }; return <section className="content-stack"><div className="section-heading page-heading"><div><span className="eyebrow">本地配置 · 不上传密钥</span><h2>接口与数据设置</h2><p>Codex 和批改接口固定使用 {REQUIRED_MODEL}；网页端临时输入的 API Key 只保留在当前会话，不会写入 localStorage。</p></div></div><div className="settings-layout"><section className="panel settings-panel"><div className="form-field"><label>Base URL</label><input value={draft.baseUrl} onChange={(event) => setDraft({ ...draft, baseUrl: event.target.value })} placeholder="https://wawapii.com" /></div><div className="form-field"><label>API Key（当前会话）</label><input type="password" value={draft.apiKey} onChange={(event) => setDraft({ ...draft, apiKey: event.target.value })} placeholder="不会保存到浏览器存储" autoComplete="off" /></div><div className="form-field"><label>模型名称（固定）</label><input value={REQUIRED_MODEL} readOnly /></div><div className="settings-actions"><button className="primary-button" onClick={save}>保存设置 <Check size={16} /></button><button className="ghost-button danger" onClick={() => { localStorage.removeItem('env867-progress'); location.reload(); }}>清除本地数据</button></div></section><aside className="panel safety-panel"><ShieldCheck size={22} /><h3>桥接说明</h3><p>Codex CLI 使用仓库配置与环境变量；前端 API Key 只在当前会话内存中使用。正式写入和构建任务仍需审批。</p></aside></div></section>; }

function chapterCards(chapterTitle: string): Card[] { return cards.filter((card) => card.chapter === chapterTitle); }
function touchActivity(activity: Record<string, number>) { const key = new Date().toISOString().slice(0, 10); return { ...activity, [key]: (activity[key] ?? 0) + 1 }; }
function EmptyState({ title, body }: { title: string; body: string }) { return <div className="empty-state"><CircleHelp size={25} /><h3>{title}</h3><p>{body}</p></div>; }
createRoot(document.getElementById('root')!).render(<App />);
