import { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BookOpen, BrainCircuit, Check, ChevronLeft, ChevronRight, CircleHelp, FileText, Home, Menu, MessageCircle, PenLine, Search, Settings, ShieldCheck, Sparkles, Target, Terminal, X } from 'lucide-react';
import './styles.css';
import { cards, chapters, defaultQuestions, type Card, type Chapter, type Question } from './content';
import { bookChapters, bookPages, bookSource } from './book-index';
import { gradeAnswer } from './lib/ai';
import { dueMemory, loadProgress, saveProgress, scheduleMemory, type MemoryState, type Progress } from './lib/storage';
import { CoachView as RemoteCoachView } from './CoachView';
import { CodexView } from './CodexView';

type View = 'home' | 'read' | 'cards' | 'review' | 'practice' | 'coach' | 'codex' | 'settings';
const titles: Record<View, string> = { home: '把知识变成得分点', read: '全文阅读与目录', cards: '主动回忆卡', review: '题库草稿审核', practice: '逐题练习', coach: '学习教练', codex: 'Codex 工作台', settings: '接口与数据设置' };
const feedback: Array<[MemoryState, string, string]> = [['again', '再来一次', '重新安排到今天'], ['hard', '困难', '约 1 天后'], ['good', '记住了', '按遗忘曲线延长'], ['easy', '很轻松', '大幅延长间隔']];

function App() {
  const [view, setView] = useState<View>('home'); const [progress, setProgress] = useState<Progress>(() => loadProgress(defaultQuestions));
  const [chapterId, setChapterId] = useState('intro'); const [pageNumber, setPageNumber] = useState(4); const [query, setQuery] = useState(''); const [mobileNav, setMobileNav] = useState(false); const [notice, setNotice] = useState('');
  const update = (next: Progress) => { setProgress(next); saveProgress(next); }; const navigate = (next: View) => { setView(next); setMobileNav(false); setNotice(''); };
  const search = query.trim().toLowerCase(); const due = dueMemory(progress.memory); const currentPage = bookPages.find((p) => p.page === pageNumber) ?? bookPages[0];
  const menu: Array<[View, string, typeof Home]> = [['home', '总览', Home], ['read', '全文阅读', BookOpen], ['cards', '主动回忆', BrainCircuit], ['review', '题库审核', FileText], ['practice', '开始练习', PenLine], ['coach', '学习教练', MessageCircle], ['codex', 'Codex 工作台', Terminal], ['settings', '接口设置', Settings]];
  return <div className="app-shell"><aside className={mobileNav ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark">867</div><div><strong>环境学学习台</strong><span>本地优先 · 可解释复习</span></div></div><nav className="main-nav">{menu.map(([id, label, Icon]) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => navigate(id)}><Icon size={18} /><span>{label}</span>{id === 'cards' && due.length > 0 && <b className="badge">{due.length}</b>}</button>)}</nav><div className="side-tip"><Target size={17} /><div><strong>今日任务</strong><span>{due.length ? `有 ${due.length} 项到期，先做主动回忆。` : '阅读 1 页，再复习 1 张卡。'}</span></div></div><div className="sidebar-footer"><span className="status-dot" />本地学习数据已保存</div></aside>{mobileNav && <button className="scrim" aria-label="关闭菜单" onClick={() => setMobileNav(false)} />}<main className="workspace"><header className="topbar"><button className="icon-button mobile-toggle" onClick={() => setMobileNav(true)} aria-label="打开菜单"><Menu size={20} /></button><div><span className="eyebrow">867 环境学 · 二期学习工作台</span><h1>{titles[view]}</h1></div><label className="search-box"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索全文、章节、卡片..." /></label></header>{notice && <div className="notice"><span>{notice}</span><button className="icon-button" onClick={() => setNotice('')}><X size={15} /></button></div>}{view === 'home' && <HomeView progress={progress} due={due.length} navigate={navigate} />}{view === 'read' && <ReadView page={currentPage} pageNumber={pageNumber} setPageNumber={setPageNumber} query={search} chapterId={chapterId} setChapterId={setChapterId} />}{view === 'cards' && <CardsView progress={progress} update={update} query={search} />}{view === 'review' && <ReviewView progress={progress} update={update} setNotice={setNotice} />}{view === 'practice' && <PracticeView progress={progress} update={update} setNotice={setNotice} />}{view === 'coach' && <RemoteCoachView progress={progress} setNotice={setNotice} />}{view === 'codex' && <CodexView progress={progress} setNotice={setNotice} />}{view === 'settings' && <SettingsView progress={progress} update={update} setNotice={setNotice} />}</main></div>;
}

function HomeView({ progress, due, navigate }: { progress: Progress; due: number; navigate: (v: View) => void }) { const completed = Object.keys(progress.grades).length; const mastered = Object.values(progress.memory).filter((i) => i.repetitions >= 3).length; return <section className="content-stack"><div className="hero-card"><div className="hero-copy"><span className="eyebrow light">今日学习路线</span><h2>从“会看”到“会答”<br />每一步都留下证据。</h2><p>全文索引、主动回忆和可解释间隔重复全部在本地运行。</p><button className="primary-button" onClick={() => navigate(due ? 'cards' : 'read')}>{due ? '开始今日复习' : '打开全文阅读'} <ArrowRight size={17} /></button></div><div className="hero-graphic"><div className="hero-ring ring-one" /><div className="hero-ring ring-two" /><div className="hero-core">867</div></div></div><div className="stats-grid"><Stat label="索引页数" value={bookPages.length} suffix=" 页" hint="来源锚点可追溯" /><Stat label="今日到期" value={due} suffix=" 项" hint="间隔重复任务" /><Stat label="已掌握" value={mastered} suffix=" 项" hint="连续 3 次以上" /><Stat label="已批改" value={completed} suffix=" 道" hint="形成反馈闭环" /></div><div className="two-column"><section className="panel"><div className="section-heading"><div><span className="eyebrow">知识地图</span><h3>十二章治理闭环</h3></div><button className="text-button" onClick={() => navigate('read')}>查看全文 <ChevronRight size={15} /></button></div><div className="roadmap-list">{chapters.map((chapter, i) => <button className="roadmap-item" key={chapter.id} onClick={() => navigate('read')}><span className="step-number">{String(i + 1).padStart(2, '0')}</span><span><strong>{chapter.title}</strong><small>{chapter.subtitle}</small></span><span className="roadmap-progress"><i style={{ width: `${progress.read.includes(chapter.id) ? 100 : 18 + i * 5}%`, background: chapter.color }} /></span><ChevronRight size={16} /></button>)}</div></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">答题链</span><h3>源 · 过程 · 后果 · 治理</h3></div><Sparkles size={19} className="gold-icon" /></div><div className="answer-chain">{[['源', '输入、排放与负荷'], ['过程', '迁移、转化与扩散'], ['后果', '质量、生态与暴露'], ['治理', '监测、控制与复盘']].map(([title, body], i) => <div className="chain-step" key={title}><span>0{i + 1}</span><strong>{title}</strong><p>{body}</p></div>)}</div></section></div></section>; }
function Stat({ label, value, suffix, hint }: { label: string; value: number; suffix: string; hint: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}<small>{suffix}</small></strong><em>{hint}</em></div>; }

function ReadView({ page, pageNumber, setPageNumber, query, chapterId, setChapterId }: { page: typeof bookPages[number]; pageNumber: number; setPageNumber: (n: number) => void; query: string; chapterId: string; setChapterId: (id: string) => void }) { const matches = query ? bookPages.filter((p) => `${p.title} ${p.text}`.toLowerCase().includes(query)) : bookPages; const jump = (n: number) => setPageNumber(Math.min(bookPages[bookPages.length - 1]?.page ?? 1, Math.max(1, n))); return <section className="content-stack"><div className="section-heading page-heading"><div><span className="eyebrow">来源锚点 · {bookSource}</span><h2>全文阅读</h2><p>已从 `structured.md` 生成 {bookPages.length} 页内容索引；页面、章节和搜索结果都保留原始页码。</p></div><div className="reader-controls"><button className="secondary-button" onClick={() => jump(pageNumber - 1)}><ChevronLeft size={16} />上一页</button><label>第 <input value={pageNumber} onChange={(e) => jump(Number(e.target.value) || 1)} /> / {bookPages.length} 页</label><button className="secondary-button" onClick={() => jump(pageNumber + 1)}>下一页<ChevronRight size={16} /></button></div></div><div className="reader-layout"><aside className="panel toc"><h3>目录</h3>{bookChapters.map((c) => <button key={c.title} className={page.title === c.title ? 'toc-item active' : 'toc-item'} onClick={() => jump(c.page)}><span>{c.page}</span>{c.title}</button>)}<hr />{matches.slice(0, 24).map((p) => <button key={p.page} className="toc-item" onClick={() => jump(p.page)}><span>{p.page}</span>{p.title}</button>)}</aside><article className="reading-card source-reader"><div className="reading-meta"><span className="chapter-label">第 {page.page} 页</span><span>来源锚点：structured.md#page-{page.page}</span></div><h3>{page.title}</h3>{page.text.split(/\n{2,}/).map((paragraph, i) => paragraph.startsWith('#') ? <h4 key={i}>{paragraph.replace(/^#+\s*/, '')}</h4> : <p key={i}>{paragraph}</p>)}</article></div></section>; }

function CardsView({ progress, update, query }: { progress: Progress; update: (p: Progress) => void; query: string }) { const visible = cards.filter((c) => !query || `${c.title}${c.body}${c.tags.join('')}`.toLowerCase().includes(query)); const [selected, setSelected] = useState<Card>(visible[0] ?? cards[0]); const [revealed, setRevealed] = useState(false); const current = visible.find((c) => c.id === selected.id) ?? visible[0] ?? cards[0]; const review = (state: MemoryState) => { const memory = scheduleMemory(progress.memory[current.id], state, current.id, 'card', current.title); update({ ...progress, memory: { ...progress.memory, [current.id]: memory } }); setRevealed(false); }; return <section className="content-stack"><div className="section-heading page-heading"><div><span className="eyebrow">主动回忆 · 间隔重复 + 遗忘曲线</span><h2>先回答，再看答案</h2><p>当前算法透明展示间隔、难度和下次复习时间，不依赖外部服务。</p></div></div><div className="card-training"><aside className="panel card-list">{visible.map((card) => <button key={card.id} className={card.id === current.id ? 'card-list-item active' : 'card-list-item'} onClick={() => { setSelected(card); setRevealed(false); }}><strong>{card.title}</strong><small>{progress.memory[card.id]?.repetitions ?? 0} 次 · {progress.memory[card.id] ? `下次 ${formatDate(progress.memory[card.id].dueAt)}` : '未学习'}</small></button>)}</aside><section className="panel recall-panel"><span className="pill">主动回忆卡</span><h2>{current.title}</h2><p className="recall-prompt">请用自己的话写出：这张卡如何迁移到一道题？</p>{revealed ? <div className="recall-answer"><strong>参考要点</strong><p>{current.body}</p></div> : <button className="secondary-button reveal-button" onClick={() => setRevealed(true)}>显示参考要点</button>}<div className="memory-feedback"><span>复习反馈</span>{feedback.map(([state, label, hint]) => <button key={state} onClick={() => review(state)}><strong>{label}</strong><small>{hint}</small></button>)}</div>{progress.memory[current.id] && <MemorySummary item={progress.memory[current.id]} />}</section></div></section>; }
function MemorySummary({ item }: { item: Progress['memory'][string] }) { return <div className="memory-summary"><span>掌握度：{Math.min(100, item.repetitions * 25 + Math.round((item.ease - 2) * 20))}%</span><span>间隔：{item.intervalDays.toFixed(1)} 天</span><span>下次：{formatDate(item.dueAt)}</span></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat('zh-CN', { month: 'numeric', day: 'numeric' }).format(new Date(value)); }

function ReviewView({ progress, update, setNotice }: { progress: Progress; update: (p: Progress) => void; setNotice: (s: string) => void }) { const drafts = progress.questions.filter((q) => q.status === 'draft'); if (!drafts.length) return <section className="content-stack"><EmptyState title="没有待审核草稿" body="当前题库草稿已经全部处理。" /></section>; return <section className="content-stack"><div className="panel review-list">{drafts.map((question) => <div className="review-item" key={question.id}><div><span className="pill">{question.type}</span><h3>{question.title}</h3><p>{question.answer}</p></div><button className="primary-button" onClick={() => { update({ ...progress, questions: progress.questions.map((q) => q.id === question.id ? { ...q, status: 'approved' } : q) }); setNotice('题目已通过审核'); }}>通过并加入练习</button></div>)}</div></section>; }

function PracticeView({ progress, update, setNotice }: { progress: Progress; update: (p: Progress) => void; setNotice: (s: string) => void }) { const questions = progress.questions.filter((q) => q.status === 'approved'); const [index, setIndex] = useState(0); const [busy, setBusy] = useState(false); if (!questions.length) return <section className="content-stack"><EmptyState title="还没有正式题目" body="请先在题库数据中加入 approved 题目。" /></section>; const q = questions[index] ?? questions[0]; const answer = progress.answers[q.id] ?? ''; const submit = async () => { setBusy(true); try { const result = await gradeAnswer(progress.settings.baseUrl, progress.settings.apiKey, progress.settings.model, q.title, answer, q.answer, q.points); update({ ...progress, grades: { ...progress.grades, [q.id]: result }, memory: { ...progress.memory, [q.id]: scheduleMemory(progress.memory[q.id], 'good', q.id, 'question', q.title) } }); setNotice('批改完成，已安排下一次复习'); } catch (e) { setNotice(e instanceof Error ? e.message : '批改失败'); } finally { setBusy(false); } }; return <section className="content-stack"><div className="practice-layout"><aside className="panel question-rail"><span className="eyebrow">题目列表</span>{questions.map((item, i) => <button key={item.id} className={item.id === q.id ? 'question-nav active' : 'question-nav'} onClick={() => setIndex(i)}>{String(i + 1).padStart(2, '0')} · {item.title}</button>)}</aside><div className="answer-panel"><div className="question-meta"><span className="pill">{q.type}</span><span>{q.difficulty}</span></div><h2>{q.title}</h2><div className="points-box"><strong>采分点</strong><div className="tag-row">{q.points.map((p) => <span key={p}>{p}</span>)}</div></div><textarea value={answer} onChange={(e) => update({ ...progress, answers: { ...progress.answers, [q.id]: e.target.value } })} placeholder="先写出你的判断链条..." /><div className="answer-footer"><span>{answer.length} 字 · 本地保存</span><button className="primary-button" disabled={busy || !answer.trim()} onClick={submit}>{busy ? '批改中...' : '提交批改'} <Sparkles size={16} /></button></div>{progress.grades[q.id] && <div className="grade-result"><strong>最近反馈</strong><p>{progress.grades[q.id]}</p></div>}</div></div></section>; }

function CoachView({ progress, update, setNotice }: { progress: Progress; update: (p: Progress) => void; setNotice: (s: string) => void }) { const [messages, setMessages] = useState<Array<{ role: 'coach' | 'user'; text: string }>>([{ role: 'coach', text: '你好，我是本地 Codex 学习教练。可以帮你定位笔记、安排复习、整理题库或发起构建任务；不会直接执行危险写操作。' }]); const [draft, setDraft] = useState(''); const [pending, setPending] = useState<string | null>(null); const tools = ['搜索平台内容', '读取学习数据', '生成复习任务', '检查题库草稿', '发起构建任务']; const send = () => { if (!draft.trim()) return; const text = draft.trim(); setMessages((m) => [...m, { role: 'user', text }, { role: 'coach', text: localCoach(text, progress) }]); setDraft(''); }; const requestTool = (tool: string) => { if (tool === '发起构建任务') setPending(tool); else setNotice(`已在本地适配层模拟：${tool}`); }; const approve = () => { setPending(null); setNotice('构建任务已获本次审批；Tauri 桥接仍需接入后端命令'); update({ ...progress }); }; return <section className="content-stack"><div className="coach-layout"><section className="panel coach-chat"><div className="coach-messages">{messages.map((m, i) => <div className={`chat-bubble ${m.role}`} key={i}>{m.text}</div>)}</div><div className="coach-input"><input value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && send()} placeholder="例如：安排今天复习水污染..." /><button className="primary-button" onClick={send}>发送</button></div></section><aside className="panel tool-panel"><div className="section-heading"><div><span className="eyebrow">受控工具 UI</span><h3>只操作平台内容</h3></div><ShieldCheck size={20} /></div><p>允许范围：平台内容、Skill、题库、学习数据、构建任务。所有危险写操作先展示审批卡。</p>{tools.map((tool) => <button className="tool-button" key={tool} onClick={() => requestTool(tool)}><span>{tool}</span><ChevronRight size={15} /></button>)}{pending && <div className="approval-card"><strong>需要审批：{pending}</strong><p>将执行一次本地构建任务，不会上传密钥或修改仓库历史。</p><button className="primary-button" onClick={approve}>批准本次操作</button><button className="ghost-button" onClick={() => setPending(null)}>取消</button></div>}</aside></div></section>; }
function localCoach(text: string, progress: Progress) { if (text.includes('复习')) return `本地建议：你有 ${dueMemory(progress.memory).length} 项到期。先从主动回忆卡开始，再做一道 ${progress.questions[0]?.difficulty ?? '基础'}题。`; if (text.includes('搜索') || text.includes('笔记')) return `本地索引已就绪：${bookPages.length} 页、${bookChapters.length} 章，可在全文阅读中按页码和来源锚点定位。`; return '本地适配层已收到请求。你可以让我搜索笔记、读取学习数据、生成任务、检查题库或发起构建。'; }

function SettingsView({ progress, update, setNotice }: { progress: Progress; update: (p: Progress) => void; setNotice: (s: string) => void }) { const [draft, setDraft] = useState(progress.settings); const save = () => { update({ ...progress, settings: { ...draft, model: 'databricks-gpt-5-6-luna' } }); setNotice('设置已保存；模型已锁定为 databricks-gpt-5-6-luna，API Key 仅保留在当前会话。'); }; return <section className="content-stack"><div className="section-heading page-heading"><div><span className="eyebrow">本地配置 · 不上传密钥</span><h2>接口与数据设置</h2><p>Codex 配置优先使用环境变量；网页端临时输入的 API Key 只保留在当前会话，不会写入 localStorage。</p></div></div><div className="settings-layout"><section className="panel settings-panel"><div className="form-field"><label>Base URL</label><input value={draft.baseUrl} onChange={(e) => setDraft({ ...draft, baseUrl: e.target.value })} placeholder="https://.../v1" /></div><div className="form-field"><label>API Key（当前会话）</label><input type="password" value={draft.apiKey} onChange={(e) => setDraft({ ...draft, apiKey: e.target.value })} placeholder="不会保存到浏览器存储" autoComplete="off" /></div><div className="form-field"><label>模型名称（固定）</label><input value="databricks-gpt-5-6-luna" readOnly /></div><div className="settings-actions"><button className="primary-button" onClick={save}>保存设置 <Check size={16} /></button><button className="ghost-button danger" onClick={() => { localStorage.removeItem('env867-progress'); location.reload(); }}>清除本地数据</button></div></section><aside className="panel safety-panel"><ShieldCheck size={22} /><h3>桥接说明</h3><p>Codex CLI 使用仓库配置与环境变量；前端 API Key 只在当前会话内存中使用。所有正式写入和构建任务都必须由审批卡触发。</p></aside></div></section>; }
function EmptyState({ title, body }: { title: string; body: string }) { return <div className="empty-state"><CircleHelp size={25} /><h3>{title}</h3><p>{body}</p></div>; }
createRoot(document.getElementById('root')!).render(<App />);
